<?php
$productId = $this->getProductId();
$conf = $this->helper('Ax\Zoom\Helper\Data')->getConfig('axzoom_options');

$ajaxzoom_initParam = $this->prepareInitParamFront($conf);

$axZmPath = $this->getBaseUrl() . 'axzoom/axZm/';
$product = $this->getProduct();
$imagesJson = $this->getImagesJson();
$images360Json = $this->images360Json($productId);
$az_gallery_position = @$conf['general_settings']['galleryPosition'];
$images360jsonComb = $this->getImagesJsonComb();
$az_img_hotspots = null;


// !!! AZ: make it like magento1 plugin
$az_img_hotspots = $this->getImageHotspotsProduct($productId);


$ajaxzoom_displayInSelector = false; // !!! $conf['plugin_settings']['displayInSelector'];
$ajaxzoom_displayInSelectorAppend = true; // !!! $conf['plugin_settings']['displayInSelectorAppend'];
$ajaxzoom_containerId = 'axZm_mouseOverWithGalleryContainer';
if (!isset($conf['plugin_settings']['displayInAzOpt'])) {
    $conf['plugin_settings']['displayInAzOpt'] = '{}';
}

$videosJson = $this->videosJson($productId);

?>


<div class="axZm_mouseOverWithGalleryContainer" id="<?php echo $ajaxzoom_containerId;?>" 
    style="<?php echo $ajaxzoom_displayInSelector ? 'display: none' : ''; ?>">

    <!-- Parent container for offset to the left or right -->
    <div class="axZm_mouseOverZoomContainerWrap">

        <!-- Alternative container for title of the images -->
        <div class="axZm_mouseOverTitleParentAbove"></div>

        <!-- Container for mouse over image -->
        <div id="<?php echo $conf['general_settings']['divID']; ?>" class="axZm_mouseOverZoomContainer">

            <!-- Optional CSS aspect ratio and message to preserve layout before JS is triggered -->
            <div class="axZm_mouseOverAspectRatio">
                <div>
                    <span><?php echo __('Image loading...'); ?></span>
                </div>
            </div>

        </div>
    </div>

    <!-- gallery with thumbs (will be filled with thumbs by javascript) -->
    <div id="<?php echo $conf['general_settings']['galleryDivID']; ?>" class="axZm_mouseOverGallery"></div>

</div>

<?php
/*
if ($this->product_has_video_html5 === true && $conf['video_settings']['videoHtml5VideoJs'] == 'true') {
    $videojs_src = (array)json_decode($conf['plugin_settings']['defaultVideoVideojsJS'], true);
    foreach ($videojs_src as $k => $v) {
        if (strstr($k, 'css') && $v) {
            echo '<link rel="stylesheet" type="text/css" href="'.$v.'" />';
        } elseif (strstr($k, 'js') && $v) {
            echo '<script type="text/javascript" src="'.$v.'"></script>';
        }
    }
}
*/
?>


<!-- AJAX-ZOOM js block -->
<script type="text/javascript">
var axBaseUrl = '<?php echo $this->getBaseUrl(); ?>';
var spConfig = {};
require(["jquery", "jquery/ui"], function() {


    var proceedMageAjaxZoom = function() {


        require(["<?php echo implode('","', $this->_loadJS())?>"], function($) {

	        var AXZMPATH = '<?php echo $axZmPath; ?>';
	        var IMAGES_JSON = <?php echo $imagesJson ?>;
	        var IMAGES_360_JSON = <?php echo $images360Json?>;

	        var images360jsonComb = jQuery.parseJSON('<?php echo json_encode($images360jsonComb); ?>');

	        window.initAxzoom = function() {
	            if (!jQuery.axZm_psh) {
	                jQuery.axZm_psh = { };
	            }

	            // Default plain images
	            jQuery.axZm_psh.IMAGES_JSON = IMAGES_JSON;
	            

	            // Default 360
	            jQuery.axZm_psh.IMAGES_360_JSON = IMAGES_360_JSON;
	            jQuery.axZm_psh.VIDEOS_JSON = <?php echo $videosJson; ?>;
	            jQuery.axZm_psh.IMAGES_HOTSPOTS = <?php echo json_encode($az_img_hotspots, JSON_FORCE_OBJECT); ?>;

	            jQuery.axZm_psh.axZmPath = '<?php echo $axZmPath; ?>';
	            jQuery.axZm_psh.shopLang = '<?php echo substr($this->_store->getLocale(), 0, 2); ?>';
	            jQuery.axZm_psh.initParam = <?php echo  $ajaxzoom_initParam; ?>;



	            jQuery.axZm_psh.divID = jQuery.axZm_psh.initParam.divID;
	            jQuery.axZm_psh.galleryDivID = jQuery.axZm_psh.initParam.galleryDivID;
	            jQuery.axZm_psh.displayInSelector = '<?php echo $ajaxzoom_displayInSelector; ?>';
	            jQuery.axZm_psh.displayInSelectorAppend = <?php echo $ajaxzoom_displayInSelectorAppend ? 'true' : 'false'; ?>;
	            jQuery.axZm_psh.containerId = '<?php echo $ajaxzoom_containerId; ?>';
	            jQuery.axZm_psh.headSelector = '<?php echo __('360° / Video'); ?>';
	            jQuery.axZm_psh.displayInAzOpt = <?php echo $conf['plugin_settings']['displayInAzOpt']; ?>;

                console.log(jQuery.axZm_psh);

	            // Colors / attributes
	            jQuery.axZm_psh.axAssociated = {};
	            window.preRenderAxzoom();
	        };

	        window.triggerAxzoom = function() {

	            if (window.jQuery === undefined || window.renderAxzoom === undefined) {
	                setTimeout(window.triggerAxzoom, 100);
	                return false;
	            } else {
	                window.initAxzoom();
	            }
	        }

	        window.triggerAxzoom();

	        $('.gallery-placeholder').css({'position': 'absolute', 'top': '-5000px'});
        });
    };

    var doubleCheckJqueryCore = function() {
        if (window.jQuery) {
            jQuery.migrateMute = 1;
            proceedMageAjaxZoom();
        } else {
            window.setTimeout(doubleCheckJqueryCore, 50);
        }
    };

    doubleCheckJqueryCore();


    

    // handle swatch click (update images if needed)
    jQuery(document).on('click', '.swatch-option', function() {
        var IMAGES_JSON = {};
        var mageSwatchRenderer = jQuery('.swatch-opt').data('mageSwatchRenderer');
        var product_id = mageSwatchRenderer.getProduct();
        if(!product_id) {
            return;
        }
        var images = mageSwatchRenderer.options.jsonConfig.images[product_id];
        jQuery.each(images, function (idx, image) {
            if(image.type == 'image') {
                var el = document.createElement('a');
                el.href = image.full;
                IMAGES_JSON[idx+1] = {'img': el.pathname, 'title': image.caption};
            }
        });
        jQuery.axZm_psh.IMAGES_JSON = IMAGES_JSON;

        setTimeout(function () {
            jQuery.axZm_psh.resetAxZoom();
        }, 500);

        
        
    });


});

</script>