<?php
$productId = $block->getProductId();
$conf = $block->conf();

$ajaxzoom_initParam = $block->prepareInitParamFront($conf);

$axZmPath = $block->getBaseUrl() . 'axzoom/axZm/';
$product = $block->getProduct();
$imagesJson = $block->getImagesJson();
$images360Json = $block->images360Json($productId);
$az_gallery_position = empty($conf['general_settings']['galleryPosition']) ? '' : $conf['general_settings']['galleryPosition'];
$images360jsonComb = $block->getImagesJsonComb();
$az_img_hotspots = null;

// !!! AZ: make it like magento1 plugin
$az_img_hotspots = $block->getImageHotspotsProduct($productId);

$ajaxzoom_displayInSelector = isset($conf['plugin_settings']['displayInSelector']) ? $conf['plugin_settings']['displayInSelector'] : false;
$ajaxzoom_displayInSelectorAppend = isset($conf['plugin_settings']['displayInSelectorAppend']) ? $conf['plugin_settings']['displayInSelectorAppend'] : false;
$ajaxzoom_containerId = 'axZm_mouseOverWithGalleryContainer';
if (!isset($conf['plugin_settings']['displayInAzOpt'])) {
    $conf['plugin_settings']['displayInAzOpt'] = '{}';
}

$videosJson = $block->videosJson($productId);

?>
<style type="text/css">
    /* AZ: magento2 default theme menuover fix */
    .axZm_mouseOverImg {
        z-index: 2 !important;
    }
</style>

<div class="axZm_mouseOverWithGalleryContainer" id="<?= $block->escapeHtml($ajaxzoom_containerId); ?>" 
    style="<?= $block->escapeHtml($ajaxzoom_displayInSelector ? 'display: none' : ''); ?>">

    <!-- Parent container for offset to the left or right -->
    <div class="axZm_mouseOverZoomContainerWrap">

        <!-- Alternative container for title of the images -->
        <div class="axZm_mouseOverTitleParentAbove"></div>

        <!-- Container for mouse over image -->
        <div id="<?= $block->escapeHtml($conf['general_settings']['divID']); ?>" class="axZm_mouseOverZoomContainer">

            <!-- Optional CSS aspect ratio and message to preserve layout before JS is triggered -->
            <div class="axZm_mouseOverAspectRatio">
                <div>
                    <span><?= $block->escapeHtml(__('Image loading...')); ?></span>
                </div>
            </div>

        </div>
    </div>

    <!-- gallery with thumbs (will be filled with thumbs by javascript) -->
    <div id="<?= $block->escapeHtml($conf['general_settings']['galleryDivID']); ?>" class="axZm_mouseOverGallery"></div>

</div>

<?php
/*
if ($this->product_has_video_html5 === true && $conf['video_settings']['videoHtml5VideoJs'] == 'true') {
    $videojs_src = (array)json_decode($conf['plugin_settings']['defaultVideoVideojsJS'], true);
    foreach ($videojs_src as $k => $v) {
        if (strstr($k, 'css') && $v) {
            echo '<link rel="stylesheet" type="text/css" href="'.$v.'" />';
        } elseif (strstr($k, 'js') && $v) {
            echo '<script type="text/javascript" src="'.$v.'"></script>';
        }
    }
}
*/
?>

<!-- AJAX-ZOOM js block -->
<script type="text/javascript">
var axBaseUrl = '<?= $block->escapeHtml($block->getBaseUrl()); ?>';
var spConfig = {};
require(["jquery", "jquery/ui"], function() {

    var images360jsonComb = jQuery.parseJSON('<?= $block->escapeJsQuote(json_encode($images360jsonComb)); ?>');

    var proceedMageAjaxZoom = function() {

        require(["<?= $block->escapeJsQuote(implode('","', $block->_loadJS())) ?>"], function($) {

            var AXZMPATH = '<?= $block->escapeHtml($axZmPath); ?>';
            var IMAGES_JSON = <?= $block->escapeJsQuote($imagesJson) ?>;
            var IMAGES_360_JSON = <?= $images360Json?>;

            window.initAxzoom = function() {
                if (!jQuery.axZm_psh) {
                    jQuery.axZm_psh = { };
                }

                // Default plain images
                jQuery.axZm_psh.IMAGES_JSON = IMAGES_JSON;
                
                // Default 360
                jQuery.axZm_psh.IMAGES_360_JSON = IMAGES_360_JSON;
                jQuery.axZm_psh.VIDEOS_JSON = <?= $block->escapeJsQuote($videosJson); ?>;
                jQuery.axZm_psh.IMAGES_HOTSPOTS = <?= $block->escapeJsQuote(json_encode($az_img_hotspots, JSON_FORCE_OBJECT)); ?>;

                jQuery.axZm_psh.axZmPath = '<?= $block->escapeHtml($axZmPath); ?>';
                jQuery.axZm_psh.shopLang = '<?= $block->escapeHtml(substr($block->_store->getLocale(), 0, 2)); ?>';
                jQuery.axZm_psh.initParam = <?= $ajaxzoom_initParam; ?>;

                jQuery.axZm_psh.divID = jQuery.axZm_psh.initParam.divID;
                jQuery.axZm_psh.galleryDivID = jQuery.axZm_psh.initParam.galleryDivID;
                jQuery.axZm_psh.displayInSelector = '<?= $block->escapeHtml($ajaxzoom_displayInSelector); ?>';
                jQuery.axZm_psh.displayInSelectorAppend = <?= $block->escapeHtml($ajaxzoom_displayInSelectorAppend ? 'true' : 'false'); ?>;
                jQuery.axZm_psh.containerId = '<?= $block->escapeHtml($ajaxzoom_containerId); ?>';
                jQuery.axZm_psh.headSelector = '<?= $block->escapeHtml(__('360° / Video')); ?>';
                jQuery.axZm_psh.displayInAzOpt = <?= $block->escapeHtml($conf['plugin_settings']['displayInAzOpt']); ?>;

                // Colors / attributes
                jQuery.axZm_psh.axAssociated = {};
                window.preRenderAxzoom();
            };

            window.triggerAxzoom = function() {

                if (window.jQuery === undefined || window.renderAxzoom === undefined) {
                    setTimeout(window.triggerAxzoom, 100);
                    return false;
                } else {
                    window.initAxzoom();
                }
            }

            window.triggerAxzoom();

            $('.gallery-placeholder').css({'position': 'absolute', 'top': '-5000px'});
        });
    };

    var doubleCheckJqueryCore = function() {
        if (window.jQuery) {
            jQuery.migrateMute = 1;
            proceedMageAjaxZoom();
        } else {
            window.setTimeout(doubleCheckJqueryCore, 50);
        }
    };

    doubleCheckJqueryCore();


    function reloadImages() {
        var IMAGES_JSON = {};
        
        var mageSwatchRenderer = jQuery('.swatch-opt').data('mageSwatchRenderer') || jQuery('.swatch-opt').data('amasty_confSwatchRenderer');

        var product_id = mageSwatchRenderer.getProduct();

        if(!product_id) {
            return;
        }

        var encoded  = images360jsonComb[product_id];

        var images = mageSwatchRenderer.options.jsonConfig.images[product_id];
        jQuery.each(images, function (idx, image) {
            if(image.type == 'image') {
                var el = document.createElement('a');
                el.href = image.full;
                IMAGES_JSON[idx+1] = {'img': el.pathname, 'title': image.caption};
            }
        });
        jQuery.axZm_psh.IMAGES_JSON = IMAGES_JSON;
        jQuery.axZm_psh.IMAGES_360_JSON = jQuery.parseJSON(decodeURIComponent(encoded.replace(/\+/g, ' ')));

        setTimeout(function () {
            jQuery.axZm_psh.resetAxZoom();
        }, 500);          
    }


    // handle swatch click (update images if needed)
    jQuery(document).on('click', '.swatch-option', function() {
        reloadImages();
    });

    jQuery(document).on('change', '.swatch-select', function() {
        reloadImages();
    });

    jQuery(document).on('change', '.super-attribute-select', function() {
        reloadImages();
    });    
});

</script>
