
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#get_number_images_span');

        jQuery('#get_number_images_button').click(function () {

            jQuery("#axzoom_getnumberimages_2d, #axzoom_getnumberimages_360").html("&#8986;");
            var params = {};
            new Ajax.Request('<?= $block->escapeHtml($block->getAjaxUrl()) ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#get_number_images_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        collectSpan.find('.collected').show();
                    }
                    jQuery('#get_number_images_message_span').text(resultText);

                    var json = response.responseJSON;

                    if (!json) {
                        json = JSON.parse(response.responseText);
                    }

                    jQuery("#axzoom_getnumberimages_2d").html(json.images2d);
                    jQuery("#axzoom_getnumberimages_360").html(json.images360);
                    jQuery("#axzoom_getnumberimages_sum").html(parseInt(json.images360) + parseInt(json.images2d));



                }
            });
        });

    });
</script>



<table>
    <tbody>
        <tr>
            <td style="padding-right: 20px; padding-top: 0px; font-size: 12px;">Unique images: </td>
            <td style="padding-top: 0px; font-size: 12px;"><span id="axzoom_getnumberimages_2d"> ⚽ </span> (from DB)</td>
        </tr>
        <tr>
            <td style="padding-top: 10px; font-size: 12px;">Images 360° / 3D: </td>
            <td style="padding-top: 10px; font-size: 12px;"><span id="axzoom_getnumberimages_360"> ⚽ </span></td>
        </tr>
        <tr>
            <td style="padding-top: 10px; font-size: 12px; padding-bottom: 10px;">Sum: </td>
            <td style="padding-top: 10px; font-size: 12px;"><span id="axzoom_getnumberimages_sum"> ⚽ </span></td>
        </tr>
    </tbody>
</table>

<?= $block->getButtonHtml() ?>
<p class="note"><?= $block->escapeHtml(__('Request total number of images')) ?></p>
<span class="collect-indicator" id="get_number_images_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?= $block->escapeHtml($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?= $block->escapeHtml($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"/>
    <span id="get_number_images_message_span"></span>
</span>