<div id="" class="entry-edit ax-tab">
	<div class="fieldset-wrapper">
		<div class="fieldset-wrapper-title admin__fieldset-wrapper-title ax-tab-title">
			<strong class="title"><?php echo __('Add clickable hotspots to product pictures') ?></strong>
		</div>
	</div>
	<div class="fieldset fieldset-wide ax-tab-content" id="group_fields9">
		<div class="hor-scroll">
tab content
		</div>
	</div>
</div>