<?php

$az_plugin_opt = $block->getPluginOptNameLabel();
$az_plugin_prod_opt = $block->getProductPluginOpt($productId);


$groups = $block->getGroups();
$groups_360 = $block->filter360data($groups);
$active = $block->isActive();

// associated products
$associated = [];
$usedProducts = $block->getUsedProducts();
foreach ($usedProducts as $p) {
    $data = $p->getData();
    $associated[$data['entity_id']] = $data['name'] . ' (' . $data['sku'] . ')';
}
?>
<style type="text/css">
.pull-right {
    float: right;
}
#pairRows input, #pairRows textarea{
    margin-bottom: 3px;
}

#pairRows textarea{
    resize:vertical;
}
</style>





<div class="entry-edit ax-tab az_container">
    <div class="fieldset-wrapper">
        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title ax-tab-title">
            <strong class="title"><?= $block->escapeHtml(__('Enable / Disable AJAX-ZOOM for this product')) ?></strong>
        </div>
    </div>
    <div class="fieldset fieldset-wide ax-tab-content" id="group_fields9">
        <div class="hor-scroll">
            <?= $block->escapeHtml(__('AJAX ZOOM enabled for detail view of this product')) ?></label>
            <br>
            <input type="radio" name="az_active" id="az_active_on" value="1" <?php if ($active == 1) :?>checked="checked"<?php endif ?>/>
            <label class="t" for="az_active_on"><?= $block->escapeHtml(__('Yes')) ?></label>
            <input type="radio" name="az_active" id="az_active_off" value="0" <?php if ($active == 0) :?>checked="checked"<?php endif ?>/>
            <label class="t" for="az_active_off"><?= $block->escapeHtml(__('No')) ?></label>
        </div>
    </div>
    <div class="fieldset fieldset-wide ax-tab-content">
        <a href="javascript: void(0)" id="az_toggle_az_settings" style="text-decoration: none">
            <span class="az_arrowhead_down az_arrowhead_span"></span>
            <?= $block->escapeHtml(__('Individual module settings for this product')) ?>
        </a>
    </div>

            <div style="display: none;" id="az_az_settings">

                <p class="message message-info">
                    <?= $block->escapeHtml(__('Override module settings for this product only.')) ?>
                    <?= $block->escapeHtml(__('It is not needed and you do not have to set them here individually.')) ?>
                    <?= $block->escapeHtml(__('This is just for testing / experimenting and demo.')) ?>
                    <?= $block->escapeHtml(__('For reference see in module settings or visit www.ajax-zoom.com/examples/example32.php')) ?>
                </p>


                <table style="width: 100%">
                    <thead>
                        <tr>
                            <th><?= $block->escapeHtml(__('Name')) ?></th>
                            <th></th>
                            <th><?= $block->escapeHtml(__('Value')) ?></th>
                            <th style="width: 120px;"></th>
                        </tr>
                    </thead>
                    <tbody id="az_pairRows_module">
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4">
                                <div class="row_">
                                    <button class="scalable add" id="az_link_add_option_module" style="margin-top: 3px;">
                                        <span><span><span><?= $block->escapeHtml(__('Add an option')) ?></span></span></span>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
                <table id="az_pairTemplate_module" style="display: none">
                    <tr>
                        <td><input type="text" name="az_pair_name_module[]" value="name_placeholder" 
                            class="az_pair_names_module form-control" data-list="az_pair_list_names">
                        </td>
                        <td style="width: 20px;">&nbsp; : &nbsp;</td>
                        <td><input type="text" name="az_pair_value_module[]" value="value_placeholder" 
                            class="az_pair_values_module form-control"></td>
                        <td style="white-space: nowrap;">
                            &nbsp;&nbsp;
                            <a class="link_textarea_option_module" href="#">
                                <?= $block->escapeHtml(__('Edit')) ?>
                            </a>
                            &nbsp;&nbsp;
                            <a class="link_remove_option_module" href="#">
                                <?= $block->escapeHtml(__('Delete')) ?>
                            </a>
                        </td>
                    </tr>
                </table>

                <div>
                    <button style="display:none;" data-but="do not remove" type="submit" name="az_submitSettings_module" 
                        id="az_submitSettings_module" class="scalable save az_biggerButton" style="margin-top: 10px;">
                        <span><span><span>Save and stay</span></span></span>
                    </button>
                    &nbsp;
                </div>
            </div>

</div>

<div class="entry-edit ax-tab">
    <div class="fieldset-wrapper">
        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title ax-tab-title">
            <strong class="title"><?= $block->escapeHtml(__('Settings for existing 360/3D')) ?></strong>
        </div>
    </div>

    <div class="fieldset fieldset-wide ax-tab-content" id="group_fields9">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label"><label for="meta_title"><?= $block->escapeHtml(__('360/3D View')) ?></label></td>
                        <td class="value">
                            <div id="az_hidden_values">
                            <?php foreach ($groups as $group) : ?>
                            <input type="hidden" name="settings[<?= $block->escapeHtml($group['id_360']) ?>]" id="settings_<?= $block->escapeHtml($group['id_360']) ?>" value="<?= urlencode($group['settings']) ?>">
                            <input type="hidden" name="comb[<?= $block->escapeHtml($group['id_360']) ?>]" id="settings_comb_<?= $block->escapeHtml($group['id_360']) ?>" value="<?= urlencode($group['combinations']) ?>">
                            
                            <?php endforeach; ?>
                            </div>
                            <select id="id_360" name="id_360" style="min-width: 100px">
                                <option value=""><?= $block->escapeHtml(__('Select')) ?></option>
                                <?php foreach ($groups as $group) : ?>
                                <option value="<?= $block->escapeHtml($group['id_360']) ?>" data-settings="<?= urlencode($group['settings']) ?>" data-combinations="[<?= urlencode($group['combinations']) ?>]"><?= $block->escapeHtml($group['name']) ?></option>
                                <?php endforeach; ?>
                            </select>                        
                        </td>
                        <td class="scope-label"><span class="nobr"></span></td>
                    </tr>
                    <tr id="pairs" style="display:none;">
                        <td class="label"><label for="meta_title"><?= $block->escapeHtml(__('Settings')) ?></label></td>
                        <td class="value">
                            <table>
                                <thead>
                                    <tr>
                                        <th><?= $block->escapeHtml(__('Name')) ?></th>
                                        <th></th>
                                        <th style="width: 220px"><?= $block->escapeHtml(__('Value')) ?></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody id="pairRows">
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="4">
                                            <div class="row_">
                                                <button class="scalable add link_add_option">
                                                    <span><span><span><?= $block->escapeHtml(__('Add an option')) ?></span></span></span>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                </tfoot>    
                            </table>
                            <table id="pairTemplate" style="display: none">
                                <tr>
                                    <td><input type="text" name="name[]" value="name_placeholder" class="pair-names"></td>
                                    <td>&nbsp; : &nbsp;</td>
                                    <td><input type="text" name="value[]" value="value_placeholder" class="pair-values"></td>
                                    <td>
                                        <a class="link_textarea_option" href="#">
                                            <?= $block->escapeHtml(__('Edit')) ?>
                                        </a>
                                        &nbsp;&nbsp;
                                        <a class="link_remove_option" href="#">
                                            <?= $block->escapeHtml(__('Delete')) ?>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <?php if (count($associated)) : ?>
                    <tr id="comb" style="display:none;">
                        <td class="label"><label for="meta_title"><?= $block->escapeHtml(__('Associated products')) ?></label></td>
                        <td class="value">
                            <button class="comb-check-all" style="margin-bottom: 10px;" value="check all" >check all</button><br>

                            <?php foreach ($associated as $id => $name) : ?>
                            <input type="checkbox" name="combinations[]" value="<?= $block->escapeHtml($id) ?>" class="settings-combinations"> <?= $block->escapeHtml($name) ?><br>
                            <?php endforeach; ?>
                            
                            <div class="" style="display: block; margin-top: 10px;">
                                <?= $block->escapeHtml(__('Same as with images you can define which 360 should be shown in conjunction with which combinations.')) ?>
                                <?= $block->escapeHtml(__('If you do not select any this 360 will be shown for all combinations.')) ?>
                            </div>                            
                        </td>
                    </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">

window.az_data_360 = <?= json_encode($groups_360); ?>;
window.az_plugin_opt = <?= json_encode($az_plugin_opt); ?>;
window.az_plugin_prod_opt = JSON.parse('<?= $az_plugin_prod_opt; ?>');
window.az_lang_success_change_status = '<?= $block->escapeHtml(__('Status of AJAX-ZOOM being enabled for this product has been changed')); ?>';
window.az_lang_settings_360_saved = '<?= $block->escapeHtml(__('Settings for 360 have been saved')); ?>';
window.az_lang_module_settings_edited = '<?= $block->escapeHtml(__('Module settings for this product have been set')); ?>';

require(["jquery",
    "<?= $block->escapeHtml($block->getBaseUrl()) ?>axzoom/jquery.editable-select.js"
    ], function($){
    
    // auto save
    $('#az_pairRows_module').on('change', 'input', function () {
        $('#az_submitSettings_module').click();
    });


    $('#az_toggle_az_settings').bind('click', function() {
        if ($('.az_arrowhead_span', $(this)).is('.az_arrowhead_down')) {
            $('.az_arrowhead_span', $(this)).removeClass('az_arrowhead_down').addClass('az_arrowhead_up');
        } else {
            $('.az_arrowhead_span', $(this)).removeClass('az_arrowhead_up').addClass('az_arrowhead_down');
        }

        $('#az_az_settings').slideToggle(150);
    } );

    $('#az_link_add_option_module').bind('click', function(e) {
        e.preventDefault();
        pairLineModule('', '');
    } );

    $('body').on('click', '.link_textarea_option_module', function(e) {
        e.preventDefault();
        var td = $(this).parent().prev();
        if ($('input', td).length == 1) { 
            var Val = $('input', td).val().replace(/"/g, "&quot;");
            $('input', td).replaceWith('<textarea class="az_pair_values_module_a form-control" type="text" name="az_pair_value[]">'+Val+'</textarea>');
        } else if ($('textarea', td).length == 1) { 
            var Val = $('textarea', td).val().replace(/"/g, "&quot;");
            $('textarea', td).replaceWith('<input class="az_pair_values_module_a form-control" type="text" value="'+Val+'" name="az_pair_value[]">');
        }
    } );

    $('body').on('click', '.link_remove_option_module', function(e) {
        e.preventDefault();
        $(this).closest('tr').remove();
        $('#az_submitSettings_module').addClass('az_save_require');
    } );

    // PLUGIN SETTINGS FOR PRODUCT
    if (window.az_plugin_opt && typeof az_plugin_opt == 'object') {
        var datalist = '<datalist id="az_plugin_opt_list">';
        $.each(az_plugin_opt, function(k, v) {
            datalist += '<option value="'+v+'">'+v+'</option>';
        } );

        datalist += '</datalist>';
        $('body').append(datalist);
        delete datalist;
    }

    function pairLineModule(name, value) { 
        if (typeof value == 'object') {
            value = JSON.stringify(value).replace(/"/g, "&quot;");
        }

        if (typeof value == 'string') {
            value = value.replace(/"/g, "&quot;");
        }

        if (name.indexOf('/') != -1) {
            name = name.split('/')[1];
        }

        var line = $("#az_pairTemplate_module").html();
        line = line.replace(/name_placeholder/g, name);
        line = line.replace(/value_placeholder/g, value);
        line = line.replace(/az_pair_names_module/g, 'az_pair_names_module_a');
        line = line.replace(/az_pair_values_module/g, 'az_pair_values_module_a');
        line = line.replace(/az_pair_list_names/g, 'az_plugin_opt_list');
        line = line.replace(/<tbody>/gi, "");
        line = line.replace(/<\/tbody>/gi, "");
        line = $(line);

        $("#az_pairRows_module").append(line);

        setTimeout(function() {
            // !!! some css/js bug
            $('input.az_pair_names_module_a', line).aZeditableSelect();
        }, 100);
    }


    function deserialize(serializedString){
        var str = decodeURI(serializedString);
        var pairs = str.split('&');
        var obj = {}, p, idx, val;
        for (var i=0, n=pairs.length; i < n; i++) {
            p = pairs[i].split('=');
            idx = p[0];

            if (idx.indexOf("[]") == (idx.length - 2)) {
                // Eh um vetor
                var ind = idx.substring(0, idx.length-2)
                if (obj[ind] === undefined) {
                    obj[ind] = [];
                }
                obj[ind].push(p[1]);
            }
            else {
                obj[idx] = p[1];
            }
        }
        return obj;
    }


    $.each(window.az_plugin_prod_opt, function(a, b) {
        pairLineModule(a, b);
    } );


    $('#az_submitSettings_module').bind('click', function(e) {
        e.preventDefault();
        $(this).blur();

        var names = [];
        var values = [];

        $('.az_pair_names_module_a[value!=name_placeholder]').each(function() { 
            var vn = $(this).val();
            names.push(vn)
        } );

        $('.az_pair_values_module_a[value!=value_placeholder]').each(function() { 
            var vv = $(this).val();
            values.push(vv)
        } );

        $('#az_submitSettings_module').removeClass('az_save_require');

        doAdminAjax360('<?= $block->escapeHtml($block->getUrlAjax('saveProductAzSettings')); ?>', { 
            "action": "saveProductAzSettings",
            "id_product": <?= $block->escapeHtml($productId); ?>,
            "names": names.join('|'),
            "values": values.join('|'),
            "ajax": 1
        }, function (data) { 
            if(jQuery.type(data) != "object") {
                if(jQuery.type(data) != "object") {
                    data = $.parseJSON(data);
                }
            }
            window.az_plugin_prod_opt = $.parseJSON(data.moduleSettings);

            $("#az_pairRows_module").empty();
            $.each(window.az_plugin_prod_opt, function(a, b) {
                pairLineModule(a, b);
            } );

            az_showSuccessMessage(az_lang_module_settings_edited);
        } );
    } );




    function ajaxSaveSettings()
    {
        var postData = deserialize($('#az_hidden_values :input').serialize());

        doAdminAjax360('<?= $block->escapeHtml($block->getUrlAjax('saveSettings')); ?>', postData, afterSaveSettings
        );
    }


    function pairLine(name, value)
    { 
        var line = $("#pairTemplate").html();
        line = line.replace(/name_placeholder/g, name);
        line = line.replace(/value_placeholder/g, value);
        line = line.replace(/<tbody>/gi, "");
        line = line.replace(/<\/tbody>/gi, "");
        $("#pairRows").append(line);
    }

    function afterSaveSettings(data) { 

        if(jQuery.type(data) != "object") {
            var data = $.parseJSON(data);
        }

        //$('#id_360').replaceWith(data.select);
        //$('#pairs').hide();
        //$('#comb').hide();
        //$('select#id_360').val('');
        az_showSuccessMessage(data.confirmations);
    } 

    function getFieldValues(class1) {
        var inputs = document.getElementsByClassName( class1 );
        var res = [];
        for (var i = 0; i < inputs.length; i++) {
            res.push(inputs[i].value);
        };
        return res;
    }

    function setPairString() {
        var names = getFieldValues('pair-names');
        var values = getFieldValues('pair-values');
        var res = {};
        for (var i = 0; i < names.length; i++) {
            if(names[i] == 'name_placeholder') continue;
            res[names[i]] = values[i];
        };
        
        $('#settings_' + $('select#id_360').val()).val(encodeURIComponent(JSON.stringify(res)));
        ajaxSaveSettings();
    }

    function setComb() {
        
        var values = [];
        $('.settings-combinations:checked').each(function () {
            values.push($(this).val());
        });
        
        $('#settings_comb_' + $('select#id_360').val()).val(encodeURIComponent(JSON.stringify(values)));
        ajaxSaveSettings();
    }
    
    $('body').on('change', '.pair-names, .pair-values', function(e) {
        setPairString();
    } );

    $('.settings-combinations').on('change', function(e) {
        setComb();
    } );


    $('.link_add_option').click(function (e) {
        e.preventDefault();
        pairLine('', '');
    } );

    $('body').on('click', '.link_remove_option', function(e) {
        e.preventDefault();
        $(this).parent().parent().remove();
        setPairString();
    } );
    
    $('body').on('click', '.link_textarea_option', function(e) {
        e.preventDefault();
        var td = $(this).parent().prev();
        if ($('input', td).length == 1) { 
            var Val = $('input', td).val();
            $('input', td).replaceWith('<textarea class="pair-values" type="text" name="value[]">'+Val+'</textarea>');
        } else if ($('textarea', td).length == 1) { 
            var Val = $('textarea', td).val();
            $('textarea', td).replaceWith('<input class="pair-values" type="text" value="'+Val+'" name="value[]">');
        }
    } );
    
    $('body').on('change', 'select#id_360', function(e) {
        
        $('#pairRows').html('');

        if($(this).val() != '') { 

            // set pairs name:value
            var settings = $.parseJSON(unescape($('option:selected', $(this)).attr('data-settings')));
            for(var k in settings) { 
                pairLine(k, settings[k])
            } 

            // set combinations checkboxes
            var combinations = $.parseJSON(unescape($('option:selected', $(this)).attr('data-combinations')))[0];
            
            $('input.settings-combinations').attr('checked', false);
            if(combinations && combinations.length) {
                for (var i = combinations.length - 1; i >= 0; i--) {
                    $('input.settings-combinations[value=' + combinations[i] + ']').attr('checked', true);
                };
            }

            $('#pairs').show();
            $('#comb').show();
        } else {
            $('#pairs').hide();
            $('#comb').hide();
        }
    });

    $('.comb-check-all:button').toggle(function() { 
        $('input.settings-combinations').attr('checked','checked');
        $(this).val('uncheck all');
        ajaxSaveSettings();
    } ,function() { 
        $('input.settings-combinations').removeAttr('checked');
        $(this).val('check all');
        ajaxSaveSettings();
    } );
});
</script>
    
