<?php
$id = 'file360';
$name = 'file360';
$url = $block->getUrlAjax("addProductImage360") . '?isAjax=true&id_product=' . $productId . '&SID=' . $_COOKIE['admin'];

$postMaxSize = $block->returnBytes(ini_get('post_max_size'));
$maxFiles = 100;
?>

<div class="form-group">
    <div class="col-lg-12">
        <input id="<?= $block->escapeHtml($id) ?>" type="file" name="<?= $block->escapeHtml($name) ?>" data-url="<?= $block->escapeHtml($url) ?>" multiple="multiple" style="width:0px;height:0px;" />
        <button class="btn btn-default" data-style="expand-right" data-size="s" type="button" id="<?= $block->escapeHtml($id) ?>-add-button">
            <i class="icon-folder-open"></i> <?= $block->escapeHtml(__('Add files...')) ?>
        </button>
    </div>
</div>

<div class="well" style="display:none">
    <div id="<?= $block->escapeHtml($id) ?>-files-list"></div>
    <button class="ladda-button btn btn-primary" data-style="expand-right" type="button" id="<?= $block->escapeHtml($id) ?>-upload-button" style="display:none;">
        <span class="ladda-label"><i class="icon-check"></i> <?= $block->escapeHtml(__('Upload files')) ?></span>
    </button>
</div>
<div class="row" style="display:none">
    <div class="alert alert-success" id="<?= $block->escapeHtml($id) ?>-success"></div>
</div>
<div class="row" style="display:none">
    <div class="alert alert-danger" id="<?= $block->escapeHtml($id) ?>-errors"></div>
</div>

<script type="text/javascript">
    function humanizeSize(bytes)
    {
        if (typeof bytes !== 'number') {
            return '';
        }

        if (bytes >= 1000000000) {
            return (bytes / 1000000000).toFixed(2) + ' GB';
        }

        if (bytes >= 1000000) {
            return (bytes / 1000000).toFixed(2) + ' MB';
        }

        return (bytes / 1000).toFixed(2) + ' KB';
    }

    require([
        'jquery',
        'mage/template',
        'Magento_Ui/js/modal/alert',
        "mage/translate",
        "jquery/file-uploader"
        ], function($){
        <?php if (isset($files) && $files) : ?>
            $('#<?= $block->escapeHtml($id) ?>-images-thumbnails').parent().show();
        <?php endif; ?>

        var <?= $block->escapeHtml($id) ?>_total_files = 0;


        $('#<?= $block->escapeHtml($id) ?>').fileupload({
            dataType: 'json',
            async: false,
            autoUpload: false,
            singleFileUploads: true,
            maxFileSize: <?= $block->escapeHtml($postMaxSize) ?>,
            start: function (e) {
                $('#<?= $block->escapeHtml($id) ?>-upload-button').unbind('click'); //Important as we bind it for every elements in add function
            },
            fail: function (e, data) {
                $('#<?= $block->escapeHtml($id) ?>-errors').html(data.errorThrown.message).parent().show();
                $('#<?= $block->escapeHtml($id) ?>-files-list').html('').parent().hide();
            },
            done: function (e, data) {
                if (data.result) {
                    if (typeof data.result.<?= $block->escapeHtml($name) ?> !== 'undefined') {
                        for (var i=0; i<data.result.<?= $block->escapeHtml($name) ?>.length; i++) {
                            if (typeof data.result.<?= $block->escapeHtml($name) ?>[i].error !== 'undefined' && data.result.<?= $block->escapeHtml($name) ?>[i].error != '') {
                                $('#<?= $block->escapeHtml($id) ?>-errors').html('<strong>'+data.result.<?= $block->escapeHtml($name) ?>[i].name+'</strong> : '+data.result.<?= $block->escapeHtml($name) ?>[i].error).parent().show();
                                $('#<?= $block->escapeHtml($id) ?>-files-list').html('').parent().hide();
                            }
                            else
                            {
                                $(data.context).appendTo($('#<?= $block->escapeHtml($id) ?>-success'));
                                $('#<?= $block->escapeHtml($id) ?>-success').parent().show();


                                if (data.result.<?= $block->escapeHtml($name) ?>[i] !== null && data.result.<?= $block->escapeHtml($name) ?>[i].status == 'ok')
                                {

                                    var response = data.result.<?= $block->escapeHtml($name) ?>[i];
                                    var cover = "icon-check-empty";
                                    var legend = '';

                                    imageLine360(response.id, response.path, response.position, cover, response.shops, legend);
                                    $("#countImage").html(parseInt($("#countImage").html()) + 1);
                                    //$("#img" + id).remove();
                                    $('#legend_1').val('');
                                }
                            }

                        }
                    }
                    $(data.context).find('button').remove();
                }
            },
        }).on('fileuploadalways', function (e, data) {
                <?= $block->escapeHtml($id) ?>_total_files--;

                if (<?= $block->escapeHtml($id) ?>_total_files == 0)
                {
                    $('#<?= $block->escapeHtml($id) ?>-upload-button').unbind('click');
                    $('#<?= $block->escapeHtml($id) ?>-files-list').parent().hide();
                }
        }).on('fileuploadadd', function(e, data) {
            if (typeof <?= $block->escapeHtml($id) ?>_max_files !== 'undefined') {
                if (<?= $block->escapeHtml($id) ?>_total_files >= <?= $block->escapeHtml($id) ?>_max_files) {
                    e.preventDefault();
                    alert('You can upload a maximum of <?= $block->escapeHtml($maxFiles) ?> files');
                    return;
                }
            }

            data.context = $('<div/>').addClass('form-group').appendTo($('#<?= $block->escapeHtml($id) ?>-files-list'));
            var file_name = $('<span/>').append('<i class="icon-picture-o"></i> <strong>'+data.files[0].name+'</strong> ('+humanizeSize(data.files[0].size)+')').appendTo(data.context);

            var button = $('<button/>').addClass('btn btn-default pull-right').prop('type', 'button').html('<i class="icon-trash"></i> Remove file').appendTo(data.context).on('click', function() {
                <?= $block->escapeHtml($id) ?>_total_files--;
                data.files = null;

                var total_elements = $(this).parent().siblings('div.form-group').length;
                $(this).parent().remove();

                if (total_elements == 0) {
                    $('#<?= $block->escapeHtml($id) ?>-files-list').html('').parent().hide();
                }
            });

            $('#<?= $block->escapeHtml($id) ?>-files-list').parent().show();
            $('#<?= $block->escapeHtml($id) ?>-upload-button').show().bind('click', function () {
                if (data.files != null)
                    data.submit();
            });

            <?= $block->escapeHtml($id) ?>_total_files++;
        }).on('fileuploadprocessalways', function (e, data) {
            var index = data.index,    file = data.files[index];

            if (file.error) {
                $('#<?= $block->escapeHtml($id) ?>-errors').append('<div class="form-group"><i class="icon-picture-o"></i> <strong>'+file.name+'</strong> ('+humanizeSize(file.size)+') : '+file.error+'</div>').parent().show();
                $('#<?= $block->escapeHtml($id) ?>-files-list').html('').parent().hide();
                $(data.context).find('button').trigger('click');
            }
        }).on('fileuploadsubmit', function (e, data) {
            var params = new Object();

            params['id_360set'] = $('#id_360set').val();
            params['form_key'] = '<?= $block->escapeHtml($block->getFormKey()) ?>';

            data.formData = params;
        }).on('fileuploadstop', function (e, data) {
            
        });

        $('#<?= $block->escapeHtml($id) ?>-add-button').on('click', function() {
            $('#<?= $block->escapeHtml($id) ?>-success').html('').parent().hide();
            $('#<?= $block->escapeHtml($id) ?>-errors').html('').parent().hide();
            $('#<?= $block->escapeHtml($id) ?>').trigger('click');
        });        
    });
</script>